(function(q,g){function A(a){return a&&Object.prototype.toString.call(a)==="[object Array]"}function r(a,b){for(var c=0,d=b.length;c<d;c++)if(a===b[c])return c;return-1}function m(a,b){if(A(a))for(var c=0,d=a.length;c<d;c++){if(b.call(a[c],c,a[c])===false)break}else for(c in a)if(a.hasOwnProperty(c))if(b.call(a[c],c,a[c])===false)break}function I(a){return a.replace(/^\s+|\s+$/g,"")}function K(a,b,c){c=c===g?",":c;return(c+b+c).indexOf(c+a+c)>=0}function C(a){return a&&/^\d+$/.test(a)?a+"px":a}function L(a){var b;
return a&&(b=/(\d+)/.exec(a))?parseInt(b[1],10):0}function T(a){function b(c){c=parseInt(c,10).toString(16).toUpperCase();return c.length>1?c:"0"+c}return a.replace(/rgb\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/ig,function(c,d,e,f){return"#"+b(d)+b(e)+b(f)})}function O(a,b){b=b===g?",":b;var c={},d=A(a)?a:a.split(b),e;m(d,function(f,h){if(e=/^(\d+)\.\.(\d+)$/.exec(h))for(var j=parseInt(e[1],10);j<=parseInt(e[2],10);j++)c[j.toString()]=true;else c[h]=true});return c}function $(a,b){return Array.prototype.slice.call(a,
b||0)}function ca(a,b){return a===g?b:a}function sa(a,b,c){if(a.addEventListener)a.addEventListener(b,c,false);else a.attachEvent&&a.attachEvent("on"+b,c)}function ia(a,b,c){if(a.removeEventListener)a.removeEventListener(b,c,false);else a.detachEvent&&a.detachEvent("on"+b,c)}function Z(a,b){if(b){var c={},d=a.ownerDocument||a.document||a;m(ub,function(f,h){c[h]=b[h]});if(!c.target)c.target=c.srcElement||d;if(c.target.nodeType===3)c.target=c.target.parentNode;if(!c.relatedTarget&&c.fromElement)c.relatedTarget=
c.fromElement===c.target?c.toElement:c.fromElement;if(c.pageX==null&&c.clientX!=null){var e=d.documentElement;d=d.body;c.pageX=c.clientX+(e&&e.scrollLeft||d&&d.scrollLeft||0)-(e&&e.clientLeft||d&&d.clientLeft||0);c.pageY=c.clientY+(e&&e.scrollTop||d&&d.scrollTop||0)-(e&&e.clientTop||d&&d.clientTop||0)}if(!c.which&&(c.charCode||c.charCode===0?c.charCode:c.keyCode))c.which=c.charCode||c.keyCode;if(!c.metaKey&&c.ctrlKey)c.metaKey=c.ctrlKey;if(!c.which&&c.button!==g)c.which=c.button&1?1:c.button&2?3:
c.button&4?2:0;switch(c.which){case 186:c.which=59;break;case 187:case 107:case 43:c.which=61;break;case 189:case 45:c.which=109;break;case 42:c.which=106;break;case 47:c.which=111;break;case 78:c.which=110;break}if(c.which>=96&&c.which<=105)c.which-=48;c.preventDefault=function(){b.preventDefault&&b.preventDefault();b.returnValue=false};c.stopPropagation=function(){b.stopPropagation&&b.stopPropagation();b.cancelBubble=true};c.stop=function(){this.preventDefault();this.stopPropagation()};return c}}
function W(a){var b=r(a,ja);if(b<0){m(ja,function(c,d){if(!d){b=c;ja[b]=a;return false}});if(b<0){b=ja.length;ja.push(a)}}b in F||(F[b]={});return b}function X(a,b,c){if(b.indexOf(",")>=0)m(b.split(","),function(){X(a,this,c)});else{var d=W(a);if(d in F&&F[d][b]!==g&&F[d][b].length>0){m(F[d][b],function(e,f){f===g&&F[d][b].splice(e,1)});ia(a,b,F[d][b][0])}else F[d][b]=[];if(F[d][b].length===0)F[d][b][0]=function(e){m(F[d][b],function(f,h){f>0&&h&&h.call(a,Z(a,e))})};r(c,F[d][b])<0&&F[d][b].push(c);
sa(a,b,F[d][b][0])}}function N(a,b,c){if(b&&b.indexOf(",")>=0)m(b.split(","),function(){N(a,this,c)});else{var d=W(a);if(b===g){if(d in F){m(F[d],function(j,k){k.length>0&&ia(a,j,k[0])});delete F[d];delete ja[d]}}else if(F[d][b]!==g&&F[d][b].length>0)if(c===g){ia(a,b,F[d][b][0]);delete F[d][b]}else{for(var e=1,f=F[d][b].length;e<f;e++)F[d][b][e]===c&&delete F[d][b][e];if(F[d][b].length==2&&F[d][b][1]===g){ia(a,b,F[d][b][0]);delete F[d][b]}var h=0;m(F[d],function(){h++});if(h<1){delete F[d];delete ja[d]}}}}
function da(a,b){if(b.indexOf(",")>=0)m(b.split(","),function(){da(a,this)});else{var c=W(a);c in F&&F[c][b]!==g&&F[c][b].length>0&&F[c][b][0]()}}function aa(a){for(var b={},c=/\s*([\w\-]+)\s*:([^;]*)(;|$)/g,d;d=c.exec(a);){var e=I(d[1].toLowerCase());d=I(T(d[2]));b[e]=d}return b}function Y(a){for(var b={},c=/\s+(?:([\w-:]+)|(?:([\w-:]+)=([^\s"'<>]+))|(?:([\w-:]+)="([^"]*)")|(?:([\w-:]+)='([^']*)'))(?=(?:\s|\/|>)+)/g,d;d=c.exec(a);)b[d[1]||d[2]||d[4]||d[6]]=(d[2]?d[3]:d[4]?d[5]:d[7])||"";return b}
function R(a){var b="";m(aa(a),function(c,d){b+=c+":"+d+";"});return b}function S(a,b,c,d){function e(k){k=k.split("/");for(var o=[],v=0,p=k.length;v<p;v++){var n=k[v];if(n=="..")o.length>0&&o.pop();else n!==""&&n!="."&&o.push(n)}return"/"+o.join("/")}function f(k,o){if(a.substr(0,k.length)===k){for(var v=[],p=0;p<o;p++)v.push("..");p=".";if(v.length>0)p+="/"+v.join("/");if(d=="/")p+="/";return p+a.substr(k.length)}else if(j=/^(.*)\//.exec(k))return f(j[1],++o)}if(!b)return a;b=b.toLowerCase();if(r(b,
["absolute","relative","domain"])<0)return a;c=c||location.protocol+"//"+location.host;if(d===g){var h=location.pathname.match(/^(\/.*)\//);d=h?h[1]:""}var j;if(j=/^(\w+:\/\/[^\/]*)/.exec(a)){if(j[1]!==c)return a}else if(/^\w+:/.test(a))return a;if(/^\//.test(a))a=c+e(a.substr(1));else/^\w+:\/\//.test(a)||(a=c+e(d+"/"+a));if(b==="relative")a=f(c+d,0).substr(2);else if(b==="absolute")if(a.substr(0,c.length)===c)a=a.substr(c.length);return a}function M(a,b,c){c=c||"";var d=b?true:false;a=a.replace(/(<pre[^>]*>)([\s\S]*?)(<\/pre>)/ig,
function(h,j,k,o){return j+k.replace(/<br[^>]*>/ig,"\n")+o});var e={},f=["xx-small","x-small","small","medium","large","x-large","xx-large"];d&&m(b,function(h,j){for(var k=h.split(","),o=0,v=k.length;o<v;o++)e[k[o]]=O(j)});a=a.replace(/((?:\r\n|\n|\r)*)<(\/)?([\w-:]+)((?:\s+|(?:\s+[\w-:]+)|(?:\s+[\w-:]+=[^\s"'<>]+)|(?:\s+[\w-:]+="[^"]*")|(?:\s+[\w-:]+='[^']*'))*)(\/)?>((?:\r\n|\n|\r)*)/g,function(h,j,k,o,v,p,n){h=j||"";k=k||"";var s=o.toLowerCase();o=v||"";p=p?" "+p:"";n=n||"";if(d&&!e[s])return"";
if(p===""&&Pa[s])p=" /";if(Qa[s]){if(k||p)n="\n"}else if(n)n=" ";if(s!=="script"&&s!=="style")h="";if(s==="font"){var x={},y="";o=o.replace(/\s*([\w-:]+)=([^\s"'<>]+|"[^"]*"|'[^']*')/g,function(w,t,u){t=t.toLowerCase();u=u||"";u=u.replace(/^["']|["']$/g,"");if(t==="color"){x.color=u;return" "}if(t==="size"){x["font-size"]=f[parseInt(u,10)-1]||"";return" "}if(t==="face"){x["font-family"]=u;return" "}if(t==="style"){y=u;return" "}return w});if(y&&!/;$/.test(y))y+=";";m(x,function(w,t){if(t!==""){if(/\s/.test(t))t=
"'"+t+"'";y+=w+":"+t+";"}});if(y)o+=' style="'+y+'"';s="span"}if(o!==""){o=o.replace(/\s*([\w-:]+)=([^\s"'<>]+|"[^"]*"|'[^']*')/g,function(w,t,u){w=t.toLowerCase();u=u||"";if(d)if(w.charAt(0)==="."||w!=="style"&&!e[s][w])return" ";if(u==="")u='""';else{if(w==="style"){u=u.substr(1,u.length-2);u=u.replace(/\s*([^\s]+?)\s*:(.*?)(;|$)/g,function(G,P,B){G=P.toLowerCase();if(d)if(!e[s].style&&!e[s]["."+G])return"";B=I(B);B=T(B);return G+":"+B+";"});u=I(u);if(u==="")return"";u='"'+u+'"'}if(r(w,["src","href"])>=
0){if(u.charAt(0)==='"')u=u.substr(1,u.length-2);u=S(u,c)}if(u.charAt(0)!=='"')u='"'+u+'"'}return" "+w+"="+u+" "});o=o.replace(/\s+(checked|selected|disabled|readonly)(\s+|$)/ig,function(w,t){var u=t.toLowerCase();if(d)if(u.charAt(0)==="."||!e[s][u])return" ";return" "+u+'="'+u+'" '});o=I(o);if(o=o.replace(/\s+/g," "))o=" "+o;return h+"<"+k+s+o+p+">"+n}else return h+"<"+k+s+p+">"+n});if(!U){a=a.replace(/<p><br\s+\/>\n<\/p>/ig,"<p>&nbsp;</p>");a=a.replace(/<br\s+\/>\n<\/p>/ig,"</p>")}return I(a)}function ka(a){if(/\.(rm|rmvb)(\?|$)/i.test(a))return"audio/x-pn-realaudio-plugin";
if(/\.(swf|flv)(\?|$)/i.test(a))return"application/x-shockwave-flash";return"video/x-ms-asf-plugin"}function ta(a){var b="<embed ";m(a,function(c,d){b+=c+'="'+d+'" '});b+="/>";return b}function ua(a,b){for(;b=b.parentNode;)if(b===a)return true;return false}function ea(a,b){b=b.toLowerCase();var c=null;if(U&&va<8){var d=a.ownerDocument.createElement("div");d.appendChild(a.cloneNode(false));d=Y(d.innerHTML.toLowerCase());if(b in d)c=d[b]}else c=a.getAttribute(b,2);if(b==="style"&&c!==null)c=R(c);return c}
function la(a,b){function c(B){if(typeof B!="string")return B;return B.replace(/([^\w\-])/g,"\\$1")}function d(B,E){return B==="*"||B.toLowerCase()===c(E.toLowerCase())}function e(B,E,D){var z=[];(B=(D.ownerDocument||D).getElementById(B.replace(/\\/g,"")))&&d(E,B.nodeName)&&ua(D,B)&&z.push(B);return z}function f(B,E,D){var z=D.ownerDocument||D,H=[],J,Q,V;if(D.getElementsByClassName){z=D.getElementsByClassName(B.replace(/\\/g,""));J=0;for(Q=z.length;J<Q;J++){V=z[J];d(E,V.nodeName)&&H.push(V)}}else if(z.querySelectorAll){z=
z.querySelectorAll((D.nodeName!=="#document"?D.nodeName+" ":"")+E+"."+B);J=0;for(Q=z.length;J<Q;J++){V=z[J];ua(D,V)&&H.push(V)}}else{z=D.getElementsByTagName(E);J=0;for(Q=z.length;J<Q;J++){V=z[J];if(V.nodeType==1)(E=V.className)&&(" "+E+" ").indexOf(" "+B+" ")>-1&&H.push(V)}}return H}function h(B,E,D,z){var H=[];D=z.getElementsByTagName(D);for(var J=0,Q=D.length;J<Q;J++){z=D[J];if(z.nodeType==1)if(E===null)ea(z,B)!==null&&H.push(z);else E===c(ea(z,B))&&H.push(z)}return H}function j(B,E){var D=[],
z,H=(z=/^((?:\\.|[^.#\s\[<>])+)/.exec(B))?z[1]:"*";if(z=/#((?:[\w\-]|\\.)+)$/.exec(B))D=e(z[1],H,E);else if(z=/\.((?:[\w\-]|\\.)+)$/.exec(B))D=f(z[1],H,E);else if(z=/\[((?:[\w\-]|\\.)+)\]/.exec(B))D=h(z[1].toLowerCase(),null,H,E);else if(z=/\[((?:[\w\-]|\\.)+)\s*=\s*['"]?((?:\\.|[^'"]+)+)['"]?\]/.exec(B)){D=z[1].toLowerCase();z=z[2];if(D==="id")H=e(z,H,E);else{if(D==="class")H=f(z,H,E);else{if(D==="name"){D=[];z=(E.ownerDocument||E).getElementsByName(z.replace(/\\/g,""));for(var J,Q=0,V=z.length;Q<
V;Q++){J=z[Q];d(H,J.nodeName)&&ua(E,J)&&J.getAttributeNode("name")&&D.push(J)}H=D}else H=h(D,z,H,E);H=H}H=H}D=H}else{H=E.getElementsByTagName(H);J=0;for(Q=H.length;J<Q;J++){z=H[J];z.nodeType==1&&D.push(z)}}return D}b=b||document;for(var k=[],o,v=/((?:\\.|[^\s>])+|[\s>])/g;o=v.exec(a);)o[1]!==" "&&k.push(o[1]);o=[];if(k.length==1)return j(k[0],b);v=false;var p,n,s,x,y,w,t,u,G,P;w=0;for(lenth=k.length;w<lenth;w++){p=k[w];if(p===">")v=true;else{if(w>0){n=[];t=0;for(G=o.length;t<G;t++){x=o[t];s=j(p,x);
u=0;for(P=s.length;u<P;u++){y=s[u];if(v)x===y.parentNode&&n.push(y);else n.push(y)}}o=n}else o=j(p,b);if(o.length===0)return[]}}return o}function ba(a){return a.get?a.get():a}function Ra(a){var b=a.split("-");a="";m(b,function(c,d){a+=c>0?d.charAt(0).toUpperCase()+d.substr(1):d});return a}function Fa(a,b,c){if(U&&va<8&&b.toLowerCase()=="class")b="className";a.setAttribute(b,""+c)}function Ga(a){if(!a)return document;return a.ownerDocument||a.document||a}function Ba(a){if(!a)return q;a=Ga(a);return a.parentWindow||
a.defaultView}function Ha(a){if(!a||!a.nodeName)return"";return a.nodeName.toLowerCase()}function vb(a,b){var c=Ba(a),d=Ra(b),e="";if(c.getComputedStyle){c=c.getComputedStyle(a,null);e=c[d]||c.getPropertyValue(b)||a.style[d]}else if(a.currentStyle)e=a.currentStyle[d]||a.style[d];return e}function fa(a){a=a||document;return a.compatMode!="CSS1Compat"?a.body:a.documentElement}function wb(a){a=fa(a);return Math.max(a.scrollHeight,a.clientHeight)}function xb(a){a=fa(a);return Math.max(a.scrollWidth,a.clientWidth)}
function Ia(){var a,b;if(U||Sa){a=fa().scrollLeft;b=fa().scrollTop}else{a=q.scrollX;b=q.scrollY}return{x:a,y:b}}function ga(a){var b=this;m(a,function(c){b[c]=this});b.length=a.length;b.doc=Ga(b[0]);b.name=Ha(b[0]);b.type=b.length>0?b[0].nodeType:null;b.win=Ba(b[0]);b._data={}}function Ta(){this.collapsed=this.startContainer===this.endContainer&&this.startOffset===this.endOffset}function Ja(a,b){function c(y,w,t){var u=y.nodeValue.length,G;if(a){G=y.cloneNode(true).splitText(w);G.splitText(t-w)}if(b){var P=
y;if(w>0)P=y.splitText(w);t<u&&P.splitText(t-w);o.push(P)}return G}function d(y,w){var t;if(y.nodeType==3){t=c(y,h,k);a&&w.appendChild(t);return false}t=y.firstChild;for(var u,G=false,P=false,B=false,E=false;t;){u=new pa(e);u.selectNode(t);G||(G=u.compareBoundaryPoints(wa,v)>0);if(G&&!P)P=u.compareBoundaryPoints(Ca,v)>=0;if(P&&!B)B=u.compareBoundaryPoints(xa,v)>0;if(B&&!E)E=u.compareBoundaryPoints(ya,v)>=0;if(E)return false;u=t.nextSibling;if(G)if(t.nodeType==1)if(P&&!B){a&&w.appendChild(t.cloneNode(true));
b&&o.push(t)}else{var D;if(a){D=t.cloneNode(false);w.appendChild(D)}if(d(t,D)===false)return false}else if(t.nodeType==3){t=t==f&&t==j?c(t,h,k):t==f?c(t,h,t.nodeValue.length):t==j?c(t,0,k):c(t,0,t.nodeValue.length);a&&w.appendChild(t)}t=u}}var e=this.doc,f=this.startContainer,h=this.startOffset,j=this.endContainer,k=this.endOffset,o=[],v=this;if(b){v=this.cloneRange();f.nodeType==3&&h===0&&this.setStart(f.parentNode,0);this.collapse(true)}var p=e.createDocumentFragment();d(v.commonAncestor(),p);for(var n=
0,s=o.length;n<s;n++){var x=o[n];x.parentNode&&x.parentNode.removeChild(x)}return a?p:this}function qa(a,b){var c;a:{for(c=b;c;){if(i(c).name==="marquee"){c=true;break a}c=c.parentNode}c=false}c||a.moveToElementText(b)}function Ua(a,b){var c=a.parentElement().ownerDocument,d=a.duplicate();d.collapse(b);var e=d.parentElement(),f=e.childNodes;if(f.length===0)return{node:e.parentNode,offset:i(e).index()};c=c;var h=0,j=false,k=a.duplicate();qa(k,e);for(var o=0,v=f.length;o<v;o++){var p=f[o],n=k.compareEndPoints("StartToStart",
d);if(n>0)j=true;if(n===0)return{node:p.parentNode,offset:o};if(p.nodeType==1){n=a.duplicate();qa(n,p);k.setEndPoint("StartToEnd",n);if(j)h+=n.text.replace(/\r\n|\n|\r/g,"").length;else h=0}else if(p.nodeType==3){k.moveStart("character",p.nodeValue.length);h+=p.nodeValue.length}j||(c=p)}if(!j&&c.nodeType==1)return{node:e,offset:i(e.lastChild).index()+1};k=a.duplicate();qa(k,e);k.setEndPoint("StartToEnd",d);h-=k.text.replace(/\r\n|\n|\r/g,"").length;return{node:c,offset:h}}function Va(a){var b=a.ownerDocument,
c=0;for(a=a.previousSibling;a;){if(a.nodeType==1)if(i(a).isSingle())c+=1;else{var d=b.body.createTextRange();qa(d,a);c+=d.text.length}else if(a.nodeType==3)c+=a.nodeValue.length;a=a.previousSibling}return c}function Wa(a,b){var c=a.ownerDocument||a,d=c.body.createTextRange();if(c==a){d.collapse(true);return d}if(a.nodeType==1){var e=a.childNodes,f,h=false,j;if(b===0){f=e[0];e=true}else{f=e[b-1];e=false}if(!f){j=c.createTextNode(" ");a.appendChild(j);f=j;h=true}if(f.nodeName.toLowerCase()==="head"){if(b===
1)e=true;if(b===2)e=false;d.collapse(e);return d}if(f.nodeType==1){qa(d,f);d.collapse(e)}else{qa(d,a);h&&a.removeChild(j);c=Va(f);c=e?c:c+f.nodeValue.length;d.moveStart("character",c)}}else if(a.nodeType==3){qa(d,a.parentNode);d.moveStart("character",b+Va(a))}return d}function pa(a){this.startContainer=a;this.startOffset=0;this.endContainer=a;this.endOffset=0;this.collapsed=true;this.doc=a}function Da(a){if(!a.nodeName){if(a.get)a=a;else a:{var b;if(U){if(a.item){b=Ga(a.item(0));b=new pa(b);b.selectNode(a.item(0));
a=b;break a}b=a.parentElement().ownerDocument;var c=Ua(a,true);a=Ua(a,false);b=new pa(b);b.setStart(c.node,c.offset);b.setEnd(a.node,a.offset)}else{c=a.startContainer;b=c.ownerDocument||c;b=new pa(b);b.setStart(c,a.startOffset);b.setEnd(a.endContainer,a.endOffset)}a=b}return a}return new pa(a)}function za(a,b,c){try{a.execCommand(b,false,c)}catch(d){}}function Xa(a,b){var c="";try{c=a.queryCommandValue(b)}catch(d){}if(typeof c!=="string")c="";return c}function Ya(a){var b=Ba(a);return b.getSelection?
b.getSelection():a.selection}function Za(a){var b=Ya(a),c;try{c=b.rangeCount>0?b.getRangeAt(0):b.createRange()}catch(d){}if(U&&(!c||!c.item&&c.parentElement().ownerDocument!==a))return null;return c}function $a(a){var b={},c,d;m(a,function(e,f){c=e.split(",");for(var h=0,j=c.length;h<j;h++){d=c[h];b[d]=f}});return b}function Ka(a,b){return ab(a,b,"*")||ab(a,b)}function ab(a,b,c){c=c||a.name;if(a.type!==1)return false;b=$a(b);var d,e;if(b[c]){c=b[c].split(",");for(var f=0,h=c.length;f<h;f++){b=c[f];
if(b==="*")return true;d=/^(\.?)([^=]+)(?:=([^=]+))?$/.exec(b);e=d[1]?"css":"attr";b=d[2];d=d[3]||"";if(d===""&&a[e](b)!=="")return true;if(d!==""&&a[e](b)===d)return true}}return false}function bb(a){for(var b=a.first();b;){var c=b.next();a.before(b);b=c}a.remove()}function cb(a,b,c){c=c||a.name;if(a.type===1){b=$a(b);if(b[c]){c=b[c].split(",");allFlag=false;for(var d=0,e=c.length;d<e;d++){b=c[d];if(b==="*"){allFlag=true;break}var f=/^(\.?)([^=]+)(?:=([^=]+))?$/.exec(b);b=f[2];f[1]?a.css(b,""):a.removeAttr(b)}allFlag&&
bb(a)}}}function ra(a){for(a=a;a.first();)a=a.first();return a}function db(a,b){a=a.clone(true);for(var c=ra(a),d=a,e=false;b;){for(;d;){if(d.name===b.name){yb(d,b.attr(),b.css());e=true}d=d.first()}e||c.append(b.clone(false));e=false;b=b.first()}return a}function yb(a,b,c){m(b,function(d,e){d!=="style"&&a.attr(d,e)});m(c,function(d,e){a.css(d,e)})}function Ea(a){var b=a.doc;this.doc=b;this.win=Ba(b);this.sel=Ya(b);this.range=a;this._preremove=this._preformat=null}function eb(a){if(a.nodeName){var b=
a.ownerDocument||a;a=Da(b).selectNodeContents(b.body).collapse(false);var c=new Ea(a);c.onchange(function(){var d=Za(b);if(d)c.range=Da(d)});c.oninput(function(){c._applyPreformat()});c.oncursormove(function(){c._preformat=null;c._preremove=null});La&&i(b).click(function(d){if(i(d.target).name==="img"){var e=Za(b);if(e)c.range=Da(e);c.range.selectNode(d.target);c.select()}});return c}return new Ea(a)}function fb(a){var b=a.moveEl,c=a.moveFn,d=a.clickEl||b,e=[document],f=[{x:0,y:0}],h=[];(a.iframeFix===
g?true:a.iframeFix)&&i("iframe").each(function(){e.push(Ma(this));f.push(i(this).pos())});d.mousedown(function(j){var k=d.get(),o=L(b.css("left")),v=L(b.css("top")),p=b.width(),n=b.height(),s=j.pageX,x=j.pageY,y=true;m(e,function(w,t){function u(B){if(y){var E=ma(f[w].x+B.pageX-s),D=ma(f[w].y+B.pageY-x);c.call(d,o,v,p,n,E,D)}B.stop()}function G(B){B.stop()}function P(B){y=false;k.releaseCapture&&k.releaseCapture();m(h,function(){i(this.doc).unbind("mousemove",this.move).unbind("mouseup",this.up).unbind("selectstart",
this.select)});B.stop()}i(t).mousemove(u).mouseup(P).bind("selectstart",G);h.push({doc:t,move:u,up:P,select:G})});k.setCapture&&k.setCapture();j.stop()})}function na(a){function b(x,y){if(f&&(a.x===g||a.y===g)){var w=L(x)||0,t=L(y)||0;if(a.alignEl){var u=a.alignEl,G=i(u).pos();w=ma(u.clientWidth/2-w/2);t=ma(u.clientHeight/2-t/2);d=w<0?G.x:G.x+w;e=t<0?G.y:G.y+t}else{G=fa(p);u=Ia();d=ma(u.x+(G.clientWidth-w)/2);e=ma(u.y+(G.clientHeight-t)/2)}d=d<0?0:C(d);e=e<0?0:C(e);s.css({left:d,top:e})}}var c=a.name||
"",d=C(a.x),e=C(a.y),f=a.z,h=C(a.width),j=C(a.height),k=a.cls,o=a.css,v=a.html,p=a.doc||document,n=a.parent||p.body,s=i('<div style="display:block;"></div>');h&&s.css("width",h);j&&s.css("height",j);f&&s.css({position:"absolute",left:d,top:e,"z-index":f});b(h,j);k&&s.addClass(k);o&&s.css(o);v&&s.html(v);i(n).append(s);return{name:c,doc:p,div:function(){return s},remove:function(){s.remove();return this},show:function(){s.show();return this},hide:function(){s.hide();return this},draggable:function(x){x=
x||{};x.moveEl=s;x.moveFn=function(y,w,t,u,G,P){if((y+=G)<0)y=0;if((w+=P)<0)w=0;s.css("left",C(y)).css("top",C(w))};fb(x);return this},resetPos:b}}function Ma(a){a=ba(a);return a.contentDocument||a.contentWindow.document}function zb(a,b,c,d){var e=['<html><head><meta charset="utf-8" /><title>KindEditor</title>',"<style>","html {margin:0;padding:0;}","body {margin:0;padding:0;}",'body, td {font:12px/1.5 "sans serif",tahoma,verdana,helvetica;}',"p {margin:5px 0;}","table {border-collapse:collapse;}",
"table.ke-zeroborder td {border:1px dotted #AAAAAA;}",".ke-flash {","\tborder:1px solid #AAAAAA;","\tbackground-image:url("+a+"common/flash.gif);","\tbackground-position:center center;","\tbackground-repeat:no-repeat;","\twidth:100px;","\theight:100px;","}",".ke-rm {","\tborder:1px solid #AAAAAA;","\tbackground-image:url("+a+"common/rm.gif);","\tbackground-position:center center;","\tbackground-repeat:no-repeat;","\twidth:100px;","\theight:100px;","}",".ke-media {","\tborder:1px solid #AAAAAA;","\tbackground-image:url("+
a+"common/media.gif);","\tbackground-position:center center;","\tbackground-repeat:no-repeat;","\twidth:100px;","\theight:100px;","}","</style>"];if(A(c))m(c,function(f,h){h!==""&&e.push('<link href="'+h+'" rel="stylesheet" />')});else c!==""&&e.push('<link href="'+c+'" rel="stylesheet" />');d&&e.push("<style>"+d+"</style>");e.push("</head><body "+(b?'class="'+b+'"':"")+"></body></html>");return e.join("")}function gb(a){var b=na(a),c=b.remove,d=C(a.width),e=C(a.height),f=i(a.srcElement),h=a.designMode===
g?true:a.designMode,j=a.themesPath,k=a.bodyClass,o=a.cssPath;a=a.cssData;var v=b.div().addClass("ke-edit"),p=i('<iframe class="ke-edit-iframe" frameborder="0"></iframe>'),n=i('<textarea class="ke-edit-textarea" kindeditor="true"></textarea>');p.css("width","100%");n.css("width","100%");b.width=function(x){v.css("width",C(x));return b};b.height=function(x){x=C(x);v.css("height",x);p.css("height",x);if(U&&va<8||document.compatMode!="CSS1Compat")x=C(L(x)-2);n.css("height",x);return b};d&&b.width(d);
e&&b.height(e);h?n.hide():p.hide();v.append(p);v.append(n);f.hide();var s=Ma(p);if(!U)s.designMode="on";s.open();s.write(zb(j,k,o,a));s.close();if(U)s.body.contentEditable="true";b.iframe=p;b.textarea=n;b.doc=s;b.remove=function(){i(s).unbind();i(s.body).unbind();i(document).unbind();var x=b.html();f.hasVal()?f.val(x):f.html(x);f.removeAttr("kindeditor");f.show();s.write("");s.clear();p.remove();n.remove();c.call(b);return b};b.html=function(x){if(h){var y=s.body;if(x===g)return i(y).html();i(y).html(x);
return b}if(x===g)return n.val();n.val(x);return b};b.design=function(x){if(x===g?!h:x){if(!h){x=b.html();h=true;b.html(x);n.hide();p.show()}}else if(h){x=b.html();h=false;b.html(x);p.hide();n.show()}b.focus();return b};b.focus=function(){h?p.get().contentWindow.focus():n.get().focus();return b};b.html(f.hasVal()?f.val(void 0):f.html(void 0));b.cmd=eb(s);return b}function hb(a,b){a.mouseover(function(){i(this).addClass("ke-toolbar-icon-outline-on")}).mouseout(function(){i(this).removeClass("ke-toolbar-icon-outline-on")}).click(function(c){b.click.call(this,
c);c.stop()})}function ib(a){var b=na(a),c=b.remove,d=a.disableMode===g?false:a.disableMode,e=a.noDisableItems===g?[]:a.noDisableItems,f=b.div(),h={};f.addClass("ke-toolbar").bind("contextmenu,mousedown,mousemove",function(j){j.preventDefault()});b.get=function(j){return h[j]};b.addItem=function(j){var k;if(j.name=="|")k=i('<span class="ke-inline-block ke-toolbar-separator"></span>');else if(j.name=="/")k=i("<br />");else{k=i('<a class="ke-inline-block ke-toolbar-icon-outline" href="#" title="'+(j.title||
"")+'"><span class="ke-inline-block ke-toolbar-icon ke-toolbar-icon-url ke-icon-'+j.name+'"></span></a>');hb(k,j)}k.data("item",j);h[j.name]=k;f.append(k)};b.remove=function(){m(h,function(j,k){k.remove()});c.call(b)};b.disable=function(j){var k;if(j===g?!d:j){m(h,function(o,v){k=v.data("item");if(k.name!=="/"&&r(k.name,e)<0){v.addClass("ke-toolbar-icon-outline-disabled");v.opacity(0.5);k.name!=="|"&&v.unbind()}});d=true}else{m(h,function(o,v){k=v.data("item");if(k.name!=="/"&&r(k.name,e)<0){v.removeClass("ke-toolbar-icon-outline-disabled");
v.opacity(1);k.name!=="|"&&hb(v,k)}});d=false}};return b}function jb(a){a.z=a.z||811213;var b=na(a),c=b.div(),d=b.remove,e=a.centerLineMode===g?true:a.centerLineMode;c.addClass("ke-menu");b.addItem=function(f){if(f.title==="-")c.append(i('<div class="ke-menu-separator"></div>'));else{var h=i('<div class="ke-menu-item"></div>'),j=i('<div class="ke-inline-block ke-menu-item-left"></div>'),k=i('<div class="ke-inline-block ke-menu-item-right"></div>'),o=C(f.height),v=f.iconClass;c.append(h);if(o){h.css("height",
o);k.css("line-height",o)}var p;if(e){p=i('<div class="ke-inline-block ke-menu-item-center"></div>');o&&p.css("height",o)}h.mouseover(function(){i(this).addClass("ke-menu-item-on");p&&p.addClass("ke-menu-item-center-on")});h.mouseout(function(){i(this).removeClass("ke-menu-item-on");p&&p.removeClass("ke-menu-item-center-on")});h.click(function(n){f.click.call(i(this));n.stop()});h.append(j);p&&h.append(p);h.append(k);if(f.checked)v="ke-icon-checked";j.html('<span class="ke-inline-block ke-toolbar-icon ke-toolbar-icon-url '+
v+'"></span>');k.html(f.title)}};b.remove=function(){i(".ke-menu-item",c.get()).remove();d.call(b)};return b}function kb(a){function b(n,s,x){n=i(n).addClass(x);e===s.toLowerCase()&&n.addClass("ke-colorpicker-cell-selected");n.attr("title",s||a.noColor);n.mouseover(function(){i(this).addClass("ke-colorpicker-cell-on")});n.mouseout(function(){i(this).removeClass("ke-colorpicker-cell-on")});n.click(function(y){a.click.call(i(this),s);y.stop()});s?n.append(i('<div class="ke-colorpicker-cell-color"></div>').css("background-color",
s)):n.html(a.noColor);h.push(n)}a.z=a.z||811213;var c=na(a),d=a.colors||[["#E53333","#E56600","#FF9900","#64451D","#DFC5A4","#FFE500"],["#009900","#006600","#99BB00","#B8D100","#60D978","#00D5FF"],["#337FE5","#003399","#4C33E5","#9933E5","#CC33E5","#EE33EE"],["#FFFFFF","#CCCCCC","#999999","#666666","#333333","#000000"]],e=(a.selectedColor||"").toLowerCase(),f=c.remove,h=[];c.div().addClass("ke-colorpicker");var j=c.doc.createElement("table");c.div().append(j);j.className="ke-colorpicker-table";j.cellPadding=
0;j.cellSpacing=0;j.border=0;var k=j.insertRow(0),o=k.insertCell(0);o.colSpan=d[0].length;b(o,"","ke-colorpicker-cell-top");for(var v=0;v<d.length;v++){k=j.insertRow(v+1);for(var p=0;p<d[v].length;p++){o=k.insertCell(p);b(o,d[v][p],"ke-colorpicker-cell")}}c.remove=function(){m(h,function(){this.unbind()});f.call(c)};return c}function lb(a){a.z=a.z||811213;var b=na(a),c=b.remove,d=C(a.width),e=C(a.height),f=b.doc,h=b.div(),j=a.title,k=i(a.body,f),o=a.previewBtn,v=a.yesBtn,p=a.noBtn,n=a.closeBtn;a=
a.shadowMode===g?true:a.shadowMode;var s=f.documentElement,x=Math.max(s.scrollWidth,s.clientWidth);s=Math.max(s.scrollHeight,s.clientHeight);h.addClass("ke-dialog").bind("click,mousedown",function(Q){Q.stopPropagation()});var y;if(a){f=f.createElement("table");f.className="ke-dialog-table";f.cellPadding=0;f.cellSpacing=0;f.border=0;h.append(f);var w=["t","m","b"],t=["l","c","r"],u,G,P,B;u=0;for(len=3;u<len;u++){P=f.insertRow(u);G=0;for(l=3;G<l;G++){B=P.insertCell(G);B.className="ke-"+w[u]+t[G];if(u==
1&&G==1)y=i(B);else B.innerHTML='<span class="ke-dialog-empty"></span>'}}y.css({width:d,height:e,"vertical-align":"top"})}else{h.addClass("ke-dialog-no-shadow");y=h}var E=i('<div class="ke-dialog-header"></div>');y.append(E);E.html(j);var D=i('<span class="ke-dialog-icon-close ke-dialog-icon-close-'+(a?"":"no-")+'shadow" title="'+n.name+'"></span>').click(n.click);E.append(D);b.draggable({clickEl:E});var z=i('<div class="ke-dialog-body"></div>');y.append(z);z.append(k);var H=i('<div class="ke-dialog-footer"></div>');
if(o||v||p)y.append(H);m([{btn:o,name:"preview"},{btn:v,name:"yes"},{btn:p,name:"no"}],function(){var Q=this.btn;if(Q){var V=i('<input type="button" class="ke-dialog-'+this.name+'" value="'+Q.name+'" />');H.append(V);V.click(Q.click)}});e&&z.height(L(e)-E.height()-H.height());var J=na({x:0,y:0,z:811212,cls:"ke-dialog-mask",width:x,height:s});b.resetPos(h.width(),h.height());b.remove=function(){J.remove();D.remove();i("input",h.get()).remove();H.remove();z.remove();E.remove();c.call(b)};b.show=function(){J.show();
h.show()};b.hide=function(){J.hide();h.hide()};return b}function mb(a){var b,c="core";if(b=/^(\w+)\.(\w+)$/.exec(a)){c=b[1];a=b[2]}return{ns:c,key:a}}function nb(a,b){b=b===g?Aa.langType:b;if(typeof a==="string"){if(!oa[b])return"no language";var c=a.length-1;if(a.substr(c)===".")return oa[b][a.substr(0,c)];c=mb(a);return oa[b][c.ns][c.key]}m(a,function(d,e){var f=mb(d);oa[b]||(oa[b]={});oa[b][f.ns]||(oa[b][f.ns]={});oa[b][f.ns][f.key]=e})}function ob(a){var b=this;m(a,function(d){b[d]=a[d];if(d===
"scriptPath"){b.themesPath=a[d]+"themes/";b.pluginsPath=a[d]+"plugins/"}});m(Aa,function(d,e){if(b[d]===g)b[d]=e});var c=i(b.srcElement);if(!b.width)b.width=c.width()||b.minWidth;if(!b.height)b.height=c.height()||b.minHeight;b.width=C(b.width);b.height=C(b.height);b.srcElement=c;b._handlers={};m(pb,function(){this.call(b,KindEditor)})}var ha=navigator.userAgent.toLowerCase(),U=ha.indexOf("msie")>-1&&ha.indexOf("opera")==-1,Na=ha.indexOf("gecko")>-1&&ha.indexOf("khtml")==-1,La=ha.indexOf("applewebkit")>
-1,Sa=ha.indexOf("opera")>-1,va=(ha=/(?:msie|firefox|webkit|opera)[\/:\s](\d+)/.exec(ha))?ha[1]:"0",ma=Math.round,i={kindeditor:"4.0 (2010-07-28)",IE:U,GECKO:Na,WEBKIT:La,OPERA:Sa,VERSION:va,each:m,isArray:A,isFunction:function(a){return a&&Object.prototype.toString.call(a)==="[object Function]"},inArray:r,inString:K,trim:I,addUnit:C,removeUnit:L,escape:function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")},unescape:function(a){return a.replace(/&lt;/g,
"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&amp;/g,"&")},toHex:T,toMap:O,toArray:$,undef:ca,json:function(a){var b;if(b=/\{[\s\S]*\}|\[[\s\S]*\]/.exec(a))a=b[0];b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;b.lastIndex=0;if(b.test(a))a=a.replace(b,function(c){return"\\u"+("0000"+c.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return eval("("+a+")");throw"JSON parse error";}},qb=O("a,abbr,acronym,applet,b,basefont,bdo,big,br,button,cite,code,del,dfn,em,font,i,iframe,img,input,ins,kbd,label,map,object,q,s,samp,script,select,small,span,strike,strong,sub,sup,textarea,tt,u,var"),Qa=O("address,applet,blockquote,button,center,dd,del,dir,div,dl,dt,fieldset,form,frameset,hr,iframe,ins,isindex,li,map,menu,noframes,noscript,object,ol,p,pre,script,table,tbody,td,tfoot,th,thead,tr,ul"),Pa=O("area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed");
O("colgroup,dd,dt,li,options,p,td,tfoot,th,thead,tr");O("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected");var rb=O("input,button,textarea,select"),Aa={designMode:true,fullscreenMode:false,filterMode:false,shadowMode:true,scriptPath:function(){for(var a=document.getElementsByTagName("script"),b,c=0,d=a.length;c<d;c++){b=a[c].src||"";if(/kindeditor[\w\-\.]*\.js/.test(b))return b.substring(0,b.lastIndexOf("/")+1)}return""}(),langType:"zh_CN",urlType:"",
newlineType:"p",resizeType:2,dialogAlignType:"page",bodyClass:"ke-content",cssPath:"",cssData:"",minWidth:550,minHeight:100,minChangeSize:5,shortcutKeys:{undo:"Z",redo:"Y",bold:"B",italic:"I",underline:"U",selectall:"A",print:"P"},items:["source","|","fullscreen","undo","redo","print","cut","copy","paste","plainpaste","wordpaste","|","justifyleft","justifycenter","justifyright","justifyfull","insertorderedlist","insertunorderedlist","indent","outdent","subscript","superscript","|","selectall","/",
"formatblock","fontname","fontsize","|","forecolor","hilitecolor","bold","italic","underline","strikethrough","removeformat","|","image","flash","media","table","hr","emoticons","link","unlink","|","about"],colors:[["#E53333","#E56600","#FF9900","#64451D","#DFC5A4","#FFE500"],["#009900","#006600","#99BB00","#B8D100","#60D978","#00D5FF"],["#337FE5","#003399","#4C33E5","#9933E5","#CC33E5","#EE33EE"],["#FFFFFF","#CCCCCC","#999999","#666666","#333333","#000000"]],htmlTags:{font:["color","size","face",
".background-color"],span:[".color",".background-color",".font-size",".font-family",".background",".font-weight",".font-style",".text-decoration",".vertical-align"],div:["align",".border",".margin",".padding",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".background",".font-style",".text-decoration",".vertical-align",".margin-left"],table:["border","cellspacing","cellpadding","width","height","align","bordercolor",".padding",".margin",".border","bgcolor",".text-align",
".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".background",".width",".height"],"td,th":["align","valign","width","height","colspan","rowspan","bgcolor",".text-align",".color",".background-color",".font-size",".font-family",".font-weight",".font-style",".text-decoration",".vertical-align",".background"],a:["href","target","name"],embed:["src","width","height","type","loop","autostart","quality",".width",".height","align","allowscriptaccess",
"/"],img:["src","width","height","border","alt","title",".width",".height","/"],hr:["/"],br:["/"],"p,ol,ul,li,blockquote,h1,h2,h3,h4,h5,h6":["align",".text-align",".color",".background-color",".font-size",".font-family",".background",".font-weight",".font-style",".text-decoration",".vertical-align",".text-indent",".margin-left"],"tbody,tr,strong,b,sub,sup,em,i,u,strike":[]}};Aa.themesPath=Aa.scriptPath+"themes/";Aa.pluginsPath=Aa.scriptPath+"plugins/";var ub="altKey,attrChange,attrName,bubbles,button,cancelable,charCode,clientX,clientY,ctrlKey,currentTarget,data,detail,eventPhase,fromElement,handler,keyCode,layerX,layerY,metaKey,newValue,offsetX,offsetY,originalTarget,pageX,pageY,prevValue,relatedNode,relatedTarget,screenX,screenY,shiftKey,srcElement,target,toElement,view,wheelDelta,which".split(","),
ja=[],F={};U&&q.attachEvent("onunload",function(){m(ja,function(a,b){b&&N(b)})});i.ctrl=function(a,b,c){b=/^\d{2,}$/.test(b)?b:b.toUpperCase().charCodeAt(0);X(a,"keydown",function(d){if(d.ctrlKey&&d.which==b&&!d.shiftKey&&!d.altKey){c.call(a);d.stop()}})};i.ready=function(a,b){function c(){if(!f){f=true;a(KindEditor)}N(b,"DOMContentLoaded");N(b,"readystatechange");N(e,"load")}function d(){if(!f){try{b.documentElement.doScroll("left")}catch(h){e.setTimeout(d,0);return}c()}}b=b||document;var e=b.parentWindow||
b.defaultView,f=false;if(b.addEventListener)X(b,"DOMContentLoaded",c);else if(b.attachEvent){X(b,"readystatechange",function(){b.readyState==="complete"&&c()});b.documentElement.doScroll&&e.frameElement===g&&d()}X(e,"load",c)};i.formatUrl=S;i.formatHtml=M;i.mediaType=ka;i.mediaAttrs=function(a){return Y(unescape(a))};i.mediaEmbed=ta;i.mediaImg=function(a,b){var c=b.width,d=b.height,e=b.type||ka(b.src),f=ta(b),h="";if(c>0)h+="width:"+c+"px;";if(d>0)h+="height:"+d+"px;";c='<img class="'+(/realaudio/i.test(e)?
"ke-rm":/flash/i.test(e)?"ke-flash":"ke-media")+'" src="'+a+'" ';if(h!=="")c+='style="'+h+'" ';c+='kesrctag="'+escape(f)+'" alt="" />';return c};i.query=function(a,b){var c=la(a,b);return c.length>0?c[0]:null};i.queryAll=la;ga.prototype={each:function(a){for(var b=0;b<this.length;b++)if(a.call(this[b],b,this[b])===false)return this;return this},bind:function(a,b){this.each(function(){X(this,a,b)});return this},unbind:function(a,b){this.each(function(){N(this,a,b)});return this},fire:function(a){if(this.length<
1)return this;da(this[0],a);return this},hasAttr:function(a){if(this.length<1)return null;return ea(this[0],a)},attr:function(a,b){var c=this;if(a===g)return Y(c.outer());if(typeof a==="object"){m(a,function(d,e){c.attr(d,e)});return c}if(b===g){b=c.length<1?null:ea(c[0],a);return b===null?"":b}c.each(function(){Fa(this,a,b)});return c},removeAttr:function(a){this.each(function(){var b=a;if(U&&va<8&&b.toLowerCase()=="class")b="className";Fa(this,b,"");this.removeAttribute(b)});return this},get:function(a){if(this.length<
1)return null;return this[a||0]},hasClass:function(a){if(this.length<1)return false;return K(a,this[0].className," ")},addClass:function(a){this.each(function(){if(!K(a,this.className," "))this.className=I(this.className+" "+a)});return this},removeClass:function(a){this.each(function(){if(K(a,this.className," "))this.className=I(this.className.replace(new RegExp("\\s*"+a+"\\s*"),""))});return this},html:function(a){if(a===g){if(this.length<1)return"";return M(this[0].innerHTML)}this.each(function(){var b=
M(a);if(this.nodeType==1)this.innerHTML=""+b});return this},hasVal:function(){if(this.length<1)return false;return!!rb[Ha(this[0])]},val:function(a){if(a===g){if(this.length<1)return"";return this.hasVal()?this[0].value:this.attr("value")}else{this.each(function(){if(rb[Ha(this)])this.value=a;else Fa(this,"value",a)});return this}},css:function(a,b){var c=this;if(a===g)return aa(c.attr("style"));if(typeof a==="object"){m(a,function(d,e){c.css(d,e)});return c}if(b===g){if(c.length<1)return"";return c[0].style[a]||
vb(c[0],a)||""}c.each(function(){this.style[Ra(a)]=b});return c},width:function(a){if(a===g){if(this.length<1)return 0;return this[0].offsetWidth}return this.css("width",C(a))},height:function(a){if(a===g){if(this.length<1)return 0;return this[0].offsetHeight}return this.css("height",C(a))},opacity:function(a){this.each(function(){if(this.style.opacity===g)this.style.filter=a==1?"":"alpha(opacity="+a*100+")";else this.style.opacity=a==1?"":a});return this},data:function(a,b){if(b===g)return this._data[a];
this._data[a]=b;return this},pos:function(){var a=this[0],b=0,c=0;if(a)if(a.getBoundingClientRect){a=a.getBoundingClientRect();c=Ia();b=a.left+c.x;c=a.top+c.y}else for(;a;){b+=a.offsetLeft;c+=a.offsetTop;a=a.offsetParent}return{x:ma(b),y:ma(c)}},clone:function(a){if(this.length<1)return new ga([]);return new ga([this[0].cloneNode(a)])},append:function(a){if(this.length<1)return this;this[0].appendChild(ba(a));return this},before:function(a){if(this.length<1)return this;this[0].parentNode.insertBefore(ba(a),
this[0]);return this},after:function(a){if(this.length<1)return this;this[0].nextSibling?this[0].parentNode.insertBefore(ba(a),this[0].nextSibling):this[0].appendChild(ba(a));return this},replaceWith:function(a){a=ba(a);if(this.length<1)return this;N(this[0]);this[0].parentNode.replaceChild(a,this[0]);this[0]=a;return this},remove:function(){var a=this;a.each(function(b,c){N(c);if(c.hasChildNodes())c.innerHTML="";c.parentNode&&c.parentNode.removeChild(c);delete a[b]});a.length=0;return a},show:function(a){return this.css("display",
a===g?"block":a)},hide:function(){return this.css("display","none")},outer:function(){if(this.length<1)return"";var a=this.doc.createElement("div");a.appendChild(this[0].cloneNode(true));return M(a.innerHTML)},isSingle:function(){return!!Pa[this.name]},isInline:function(){return!!qb[this.name]},isBlock:function(){return!!Qa[this.name]},contains:function(a){if(this.length<1)return false;return ua(this[0],ba(a))},parent:function(){if(this.length<1)return null;var a=this[0].parentNode;return a?new ga([a]):
null},children:function(){if(this.length<1)return[];for(var a=[],b=this[0].firstChild;b;){if(b.nodeType!=3||I(b.nodeValue)!=="")a.push(new ga([b]));b=b.nextSibling}return a},first:function(){var a=this.children();return a.length>0?a[0]:null},last:function(){var a=this.children();return a.length>0?a[a.length-1]:null},index:function(){if(this.length<1)return-1;for(var a=-1,b=this[0];b;){a++;b=b.previousSibling}return a},prev:function(){if(this.length<1)return null;var a=this[0].previousSibling;return a?
new ga([a]):null},next:function(){if(this.length<1)return null;var a=this[0].nextSibling;return a?new ga([a]):null},scan:function(a,b){function c(d){for(d=b?d.firstChild:d.lastChild;d;){var e=b?d.nextSibling:d.previousSibling;if(a(d)===false)return false;if(c(d)===false)return false;d=e}}if(!(this.length<1)){b=b===g?true:b;c(this[0]);return this}}};m("blur,focus,focusin,focusout,load,resize,scroll,unload,click,dblclick,mousedown,mouseup,mousemove,mouseover,mouseout,mouseenter,mouseleave,change,select,submit,keydown,keypress,keyup,error".split(","),
function(a,b){ga.prototype[b]=function(c){return c?this.bind(b,c):this.fire(b)}});Na=i;i=function(a,b){function c(j){j[0]||(j=[]);return new ga(j)}if(typeof a==="string"){if(b)b=ba(b);var d=a.length;if(a.charAt(0)==="@")a=a.substr(1);if(a.length!==d||/<.+>/.test(a)){d=(b?b.ownerDocument||b:document).createElement("div");var e=[];if(d.nodeType==1)d.innerHTML=""+a;for(var f=0,h=d.childNodes.length;f<h;f++)e.push(d.childNodes[f]);return c(e)}return c(la(a,b))}if(a&&a.get)return a;if(A(a))return c(a);
return c($(arguments))};m(Na,function(a,b){i[a]=b});if(q.K===g)q.K=i;q.KindEditor=i;var Ca=0,wa=1,xa=2,ya=3;pa.prototype={commonAncestor:function(){function a(k){for(var o=[];k;){o.push(k);k=k.parentNode}return o}for(var b=a(this.startContainer),c=a(this.endContainer),d=0,e=b.length,f=c.length,h,j;++d;){h=b[e-d];j=c[f-d];if(!h||!j||h!==j)break}return b[e-d+1]},setStart:function(a,b){var c=this.doc;this.startContainer=a;this.startOffset=b;if(this.endContainer===c){this.endContainer=a;this.endOffset=
b}Ta.call(this);return this},setEnd:function(a,b){var c=this.doc;this.endContainer=a;this.endOffset=b;if(this.startContainer===c){this.startContainer=a;this.startOffset=b}Ta.call(this);return this},setStartBefore:function(a){return this.setStart(a.parentNode||this.doc,i(a).index())},setStartAfter:function(a){return this.setStart(a.parentNode||this.doc,i(a).index()+1)},setEndBefore:function(a){return this.setEnd(a.parentNode||this.doc,i(a).index())},setEndAfter:function(a){return this.setEnd(a.parentNode||
this.doc,i(a).index()+1)},selectNode:function(a){return this.setStartBefore(a).setEndAfter(a)},selectNodeContents:function(a){var b=i(a);if(b.type==3||b.isSingle())return this.selectNode(a);b=b.children();if(b.length>0)return this.setStartBefore(b[0].get()).setEndAfter(b[b.length-1].get());return this.setStart(a,0).setEnd(a,0)},collapse:function(a){if(a)return this.setEnd(this.startContainer,this.startOffset);return this.setStart(this.endContainer,this.endOffset)},compareBoundaryPoints:function(a,
b){var c=this.get(),d=b.get();if(this.doc.createRange)return c.compareBoundaryPoints(a,d);else{var e={};e[Ca]="StartToStart";e[wa]="EndToStart";e[xa]="EndToEnd";e[ya]="StartToEnd";c=c.compareEndPoints(e[a],d);if(c!==0)return c;var f,h,j,k;if(a===Ca||a===ya){f=this.startContainer;j=this.startOffset}if(a===wa||a===xa){f=this.endContainer;j=this.endOffset}if(a===Ca||a===wa){h=b.startContainer;k=b.startOffset}if(a===xa||a===ya){h=b.endContainer;k=b.endOffset}if(f===h){f=j-k;return f>0?1:f<0?-1:0}for(c=
h;c&&c.parentNode!==f;)c=c.parentNode;if(c)return i(c).index()>=j?-1:1;for(c=f;c&&c.parentNode!==h;)c=c.parentNode;if(c)return i(c).index()>=k?1:-1}},cloneRange:function(){return(new pa(this.doc)).setStart(this.startContainer,this.startOffset).setEnd(this.endContainer,this.endOffset)},toString:function(){var a=this.get();return(this.doc.createRange?a.toString():a.text).replace(/\r\n|\n|\r/g,"")},cloneContents:function(){return Ja.call(this,true,false)},deleteContents:function(){return Ja.call(this,
false,true)},extractContents:function(){return Ja.call(this,true,true)},insertNode:function(a){var b=this.startContainer,c=this.startOffset,d=this.endContainer,e=this.endOffset,f,h,j,k=1;if(a.nodeName.toLowerCase()==="#document-fragment"){f=a.firstChild;h=a.lastChild;k=a.childNodes.length}if(b.nodeType==1)if(j=b.childNodes[c]){b.insertBefore(a,j);if(b===d)e+=k}else b.appendChild(a);else if(b.nodeType==3)if(c===0){b.parentNode.insertBefore(a,b);if(b.parentNode===d)e+=k}else if(c>=b.nodeValue.length)b.nextSibling?
b.parentNode.insertBefore(a,b.nextSibling):b.parentNode.appendChild(a);else{j=b.splitText(c);b.parentNode.insertBefore(a,j);if(b===d){d=j;e-=c}}f?this.setStartBefore(f).setEndAfter(h):this.selectNode(a);if(this.compareBoundaryPoints(xa,this.cloneRange().setEnd(d,e))>=1)return this;return this.setEnd(d,e)},surroundContents:function(a){a.appendChild(this.extractContents());return this.insertNode(a).selectNode(a)},isControl:function(){var a=this.startContainer,b=this.startOffset,c=this.endContainer,
d=this.endOffset;return a.nodeType==1&&a===c&&b+1===d&&i(a.childNodes[b]).name==="img"},get:function(a){var b=this.doc,c=this.startContainer,d=this.startOffset,e=this.endContainer,f=this.endOffset;if(b.createRange){a=b.createRange();try{a.setStart(c,d);a.setEnd(e,f)}catch(h){}return a}if(a&&this.isControl()){a=b.body.createControlRange();a.addElement(c.childNodes[d]);return a}a=b.body.createTextRange();a.setEndPoint("StartToStart",Wa(c,d));a.setEndPoint("EndToStart",Wa(e,f));return a},html:function(){return i(this.cloneContents()).outer()}};
i.range=Da;i.START_TO_START=Ca;i.START_TO_END=wa;i.END_TO_END=xa;i.END_TO_START=ya;var sb=O("9,32,48..57,59,61,65..90,106,109..111,188,190..192,219..222"),tb=O("8,13,33..40,46"),Oa={};m(sb,function(a,b){Oa[a]=b});m(tb,function(a,b){Oa[a]=b});Ea.prototype={select:function(){var a=this.sel,b=this.range.cloneRange(),c=b.startContainer,d=c.ownerDocument||c,e=Ba(d);if(U&&c.nodeType==1&&b.collapsed){a=i("<span>&nbsp;</span>",d);b.insertNode(a.get());b=d.body.createTextRange();b.moveToElementText(a.get());
b.collapse(false);b.select();a.remove();e.focus();return this}b=b.get(true);if(U)b.select();else{a.removeAllRanges();a.addRange(b)}e.focus();return this},wrap:function(a){function b(p,n,s){var x=p.nodeValue.length,y=p;if(!(s<=n)){if(n>0)y=p.splitText(n);s<x&&y.splitText(s-n);var w;s=i(y);n=h==p;for(p=k==p;(w=s.parent())&&w.isInline()&&w.children().length==1;){n||(n=h==w.get());p||(p=k==w.get());s=w}w=s;s=f;s=s.clone(true);if(w.type==3){ra(s).append(w.clone(false));w.before(s);w.remove()}else{x=w;
for(var t;(t=w.first())&&t.children().length==1;)w=t;for(y=w.doc.createDocumentFragment();t=w.first();){t.next();y.appendChild(t.get())}s=db(x,s);y.firstChild&&ra(s).append(y);x.before(s);x.remove()}t=s.get();n&&e.setStartBefore(t);p&&e.setEndAfter(t)}}function c(p){var n=p.firstChild;if(p.nodeType==3){b(p,j,o);return false}for(var s;n;){p=Da(d);p.selectNode(n);if(p.compareBoundaryPoints(ya,e)>=0)return false;s=n.nextSibling;if(p.compareBoundaryPoints(wa,e)>0)if(n.nodeType==1){if(c(n)===false)return false}else if(n.nodeType==
3)if(n==h&&n==k)b(n,j,o);else if(n==h)b(n,j,n.nodeValue.length);else n==k?b(n,0,o):b(n,0,n.nodeValue.length);n=s}}var d=this.doc,e=this.range,f,h=e.startContainer,j=e.startOffset,k=e.endContainer,o=e.endOffset;f=typeof a=="string"?i(a,d):a;if(e.collapsed){if(this._preformat)f=db(this._preformat.wrapper,f);a=0;if(h.nodeType==3)a=h.nodeValue.length;else if(j>0)a=h.childNodes[j-1].nodeValue.length;this._preformat={wrapper:f,textLength:a,range:e.cloneRange()};return this}if(!f.isInline()){for(var v=a=
f.clone(true);v.first();)v=v.first();v.append(e.extractContents());e.insertNode(a.get()).selectNode(a.get());return this}c(e.commonAncestor());return this},split:function(a,b){for(var c=this.range,d=c.doc,e=c.cloneRange().collapse(a),f=e.startContainer,h=e.startOffset,j=f.nodeType==3?f.parentNode:f,k=false,o;j&&j.parentNode;){o=i(j);if(!o.isInline())break;if(!Ka(o,b))break;k=true;j=j.parentNode}if(k){d=d.createElement("span");c.cloneRange().collapse(!a).insertNode(d);a?e.setStartBefore(j.firstChild).setEnd(f,
h):e.setStart(f,h).setEndAfter(j.lastChild);f=e.extractContents();h=f.firstChild;k=f.lastChild;if(a){e.insertNode(f);c.setStartAfter(k).setEndBefore(d)}else{j.appendChild(f);c.setStartBefore(d).setEndBefore(h)}e=d.parentNode;e.removeChild(d);!a&&e===c.endContainer&&c.setEnd(c.endContainer,c.endOffset-1)}return this},remove:function(a){var b=this.range;if(b.collapsed){this._preremove={map:a,range:b.cloneRange()};return this}this.split(true,a);this.split(false,a);var c=[];i(b.commonAncestor()).scan(function(k){c.push(i(k))});
var d=b.startContainer,e=b.startOffset,f=b.endContainer,h=b.endOffset;if(e>0){var j=i(d.childNodes[e-1]);if(j&&ra(j).isInline()){j.remove();b.setStart(d,e-1);d==f&&b.setEnd(f,h-1)}if((j=i(d.childNodes[e]))&&ra(j).isInline()){j.remove();d==f&&b.setEnd(f,h-1)}}(b=i(f.childNodes[b.endOffset]))&&ra(b).isInline()&&b.remove();m(c,function(){cb(this,a,"*");cb(this,a)});return this},_applyPreformat:function(){var a=this.range,b=a.startContainer,c=a.startOffset,d=this._preformat,e=this._preremove;if(d||e){d?
a.setStart(d.range.startContainer,d.range.startOffset):a.setStart(e.range.startContainer,e.range.startOffset);if(d){a.collapsed&&c>0&&a.setStart(b.childNodes[c-1],d.textLength);this.wrap(d.wrapper)}if(e){if(a.collapsed){this._preremove=this._preformat=null;return}this.remove(e.map)}b=a.startContainer;c=a.startOffset;b=ra(i(b.nodeType==3?b:b.childNodes[c])).get();a.setEnd(b,b.nodeValue.length);a.collapse(false);this.select();this._preremove=this._preformat=null}},commonNode:function(a){var b=this.range,
c=b.endContainer;b=b.endOffset;for(b=c=c.nodeType==3||b===0?c:c.childNodes[b-1];b&&(b=b.firstChild)&&b.childNodes.length==1;)if(Ka(i(b),a))return i(b);for(;c;){if(Ka(i(c),a))return i(c);c=c.parentNode}return null},state:function(a){var b=this.doc,c=false;try{c=b.queryCommandState(a)}catch(d){}return c},val:function(a){var b=this.doc;a=a.toLowerCase();var c="";if(a==="fontfamily"||a==="fontname"){c=Xa(b,"fontname");c=c.replace(/['"]/g,"");return c.toLowerCase()}if(a==="formatblock"){c=Xa(b,a);if(c===
"")if(a=this.commonNode({"h1,h2,h3,h4,h5,h6,p,div,pre,address":"*"}))c=a.name;if(c==="Normal")c="p";return c.toLowerCase()}if(a==="fontsize"){if(a=this.commonNode({"*":".font-size"}))c=a.css("font-size");return c.toLowerCase()}if(a==="forecolor"){if(a=this.commonNode({"*":".color"}))c=a.css("color");c=T(c);if(c==="")c="default";return c.toLowerCase()}if(a==="hilitecolor"){if(a=this.commonNode({"*":".background-color"}))c=a.css("background-color");c=T(c);if(c==="")c="default";return c.toLowerCase()}if(a===
"createlink"){if(a=this.commonNode({a:"*"}))c=a.attr("href");return c}return c},toggle:function(a,b){this.commonNode(b)?this.remove(b):this.wrap(a);return this.select()},bold:function(){return this.toggle("<strong></strong>",{span:".font-weight=bold",strong:"*",b:"*"})},italic:function(){return this.toggle("<em></em>",{span:".font-style=italic",em:"*",i:"*"})},underline:function(){return this.toggle("<u></u>",{span:".text-decoration=underline",u:"*"})},strikethrough:function(){return this.toggle("<s></s>",
{span:".text-decoration=line-through",s:"*"})},forecolor:function(a){return this.toggle('<span style="color:'+a+';"></span>',{span:".color="+a,font:"color"})},hilitecolor:function(a){return this.toggle('<span style="background-color:'+a+';"></span>',{span:".background-color="+a})},fontsize:function(a){return this.toggle('<span style="font-size:'+a+';"></span>',{span:".font-size="+a,font:"size"})},fontname:function(a){return this.fontfamily(a)},fontfamily:function(a){return this.toggle('<span style="font-family:'+
a+';"></span>',{span:".font-family="+a,font:"face"})},removeformat:function(){var a={"*":"class,style"};m(qb,function(b){a[b]="*"});this.remove(a);return this.select()},inserthtml:function(a){var b=this.doc,c=this.range,d=b.createDocumentFragment();i("@"+a,b).each(function(){d.appendChild(this)});c.deleteContents();c.insertNode(d);c.collapse(false);return this.select()},hr:function(){return this.inserthtml("<hr />")},print:function(){this.win.print();return this},insertimage:function(a,b,c,d,e,f){b=
ca(b,"");e=ca(e,0);a='<img src="'+a+'" ';if(c)a+='width="'+c+'" ';if(d)a+='height="'+d+'" ';if(b)a+='title="'+b+'" ';if(f)a+='align="'+f+'" ';a+='alt="'+b+'" ';a+='border="'+e+'" />';return this.inserthtml(a)},createlink:function(a,b){var c=this.doc,d=this.range;this.select();var e=this.commonNode({a:"*"});if(e&&!d.isControl()){d.selectNode(e.get());this.select()}if(d.collapsed){c='<a href="'+a+'"';if(b)c+=' target="'+b+'"';c+=">"+a+"</a>";this.inserthtml(c);return this}za(c,"createlink","__ke_temp_url__");
e=this.commonNode({a:"*"});i('a[href="__ke_temp_url__"]',e?e.parent():c).each(function(){i(this).attr("href",a);b?i(this).attr("target",b):i(this).removeAttr("target")});return this},unlink:function(){var a=this.doc,b=this.range;this.select();if(b.collapsed){var c=this.commonNode({a:"*"});if(c){b.selectNode(c.get());this.select()}za(a,"unlink",null);if(La&&i(b.startContainer).name==="img"){a=i(b.startContainer).parent();a.name==="a"&&bb(a)}return this}za(a,"unlink",null);return this},oninput:function(a){i(this.doc).keyup(function(b){if(!b.ctrlKey&&
!b.altKey&&sb[b.which]){a(b);b.stop()}});return this},oncursormove:function(a){var b=this.doc;i(b).keyup(function(c){if(!c.ctrlKey&&!c.altKey&&tb[c.which]){a(c);c.stop()}});i(b).mouseup(a);return this},onchange:function(a){function b(e){setTimeout(function(){a(e)},1)}var c=this.doc,d=c.body;i(c).keyup(function(e){if(!e.ctrlKey&&!e.altKey&&Oa[e.which]){a(e);e.stop()}});i(c).mouseup(a);c!==document&&i(document).mousedown(a);i(d).bind("paste",b);i(d).bind("cut",b);return this}};m("formatblock,selectall,justifyleft,justifycenter,justifyright,justifyfull,insertorderedlist,insertunorderedlist,indent,outdent,subscript,superscript".split(","),
function(a,b){Ea.prototype[b]=function(c){za(this.doc,b,c);return this}});m("cut,copy,paste".split(","),function(a,b){Ea.prototype[b]=function(){if(!this.doc.queryCommandSupported(b))throw"not supported";za(this.doc,b,null);return this}});i.cmd=eb;i.widget=na;i.edit=gb;i.iframeDoc=Ma;i.toolbar=ib;i.menu=jb;i.colorpicker=kb;i.dialog=lb;i.tabs=function(a){var b=na(a),c=b.remove,d=a.afterSelect;a=b.div();var e=[];a.addClass("ke-tabs").bind("contextmenu,mousedown,mousemove",function(h){h.preventDefault()});
var f=i('<ul class="ke-tabs-ul ke-clearfix"></ul>');a.append(f);b.add=function(h){var j=i('<li class="ke-tabs-li">'+h.title+"</li>");j.data("tab",h);e.push(j);f.append(j)};b.selectedIndex=0;b.select=function(h){b.selectedIndex=h;m(e,function(j,k){k.unbind();if(j===h){k.addClass("ke-tabs-li-selected");i(k.data("tab").panel).show("")}else{k.removeClass("ke-tabs-li-selected").removeClass("ke-tabs-li-on").mouseover(function(){i(this).addClass("ke-tabs-li-on")}).mouseout(function(){i(this).removeClass("ke-tabs-li-on")}).click(function(){b.select(j)});
i(k.data("tab").panel).hide()}});d&&d.call(b,h)};b.remove=function(){m(e,function(){this.remove()});f.remove();c.call(b)};return b};var pb=[],oa={};ob.prototype={lang:function(a){return nb(a,this.langType)},handler:function(a,b){var c=this;c._handlers[a]||(c._handlers[a]=[]);if(b===g){m(c._handlers[a],function(){this.call(c)});return c}c._handlers[a].push(b);return c},clickToolbar:function(a,b){return this.handler("clickToolbar"+a,b)},afterCreate:function(a){return this.handler("afterCreate",a)},
beforeHideMenu:function(a){return this.handler("beforeHideMenu",a)},create:function(){function a(){b.container&&b.resize(fa().clientWidth,fa().clientHeight)}var b=this,c=b.fullscreenMode;if(c)fa().style.overflow="hidden";else fa().style.overflow="auto";var d=c?xb()+"px":b.width,e=c?wb()+"px":b.height,f=i('<div class="ke-container"></div>').css("width",d);if(c){var h=Ia();f.css({position:"absolute",left:C(h.x),top:C(h.y),"z-index":811211});i(document.body).append(f)}else b.srcElement.before(f);var j=
ib({parent:f,noDisableItems:"source,fullscreen".split(",")});m(b.items,function(v,p){j.addItem({name:p,title:b.lang(p),click:function(){if(b.menu){var n=b.menu.name;b.hideMenu();if(n===p)return}b.clickToolbar(p)}})});b.designMode||j.disable(true);h=gb({parent:f,srcElement:b.srcElement,designMode:b.designMode,themesPath:b.themesPath,bodyClass:b.bodyClass,cssPath:b.cssPath,cssData:b.cssData});i(h.doc,document).click(function(){b.menu&&b.hideMenu()});var k=i('<div class="ke-statusbar"></div>'),o;f.append(k);
if(!c){o=i('<span class="ke-inline-block ke-statusbar-right-icon"></span>');k.append(o);fb({moveEl:f,clickEl:o,moveFn:function(v,p,n,s,x,y){n+=x;s+=y;n>=b.minWidth&&b.resize(n,null);s>=b.minHeight&&b.resize(null,s)}})}if(b._resizeListener){i(q).unbind("resize",b._resizeListener);b._resizeListener=null}if(b.fullscreenMode){i(q).bind("resize",a);b._resizeListener=a}b.container=f;b.toolbar=j;b.edit=h;b.statusbar=k;b.menu=b.dialog=null;b._rightIcon=o;b.resize(d,e);b.afterCreate();return b},remove:function(){this.menu&&
this.hideMenu();this.dialog&&this.hideDialog();this.toolbar.remove();this.edit.remove();this._rightIcon&&this._rightIcon.remove();this.statusbar.remove();this.container.remove();this.container=this.toolbar=this.edit=this.menu=this.dialog=null;return this},resize:function(a,b){a!==null&&this.container.css("width",C(a));if(b!==null){b=L(b)-this.toolbar.div().height()-this.statusbar.height()-11;b>0&&this.edit.height(b)}return this},select:function(){this.edit.cmd.select();return this},html:function(a){if(a===
g)return this.edit.html();this.edit.html(a);return this},insertHtml:function(a){this.edit.cmd.inserthtml(a);return this},val:function(a){return this.edit.cmd.val(a)},state:function(a){return this.edit.cmd.state(a)},exec:function(a){var b=this.edit.cmd;b[a].apply(b,$(arguments,1));return this},focus:function(){this.edit.focus();return this},fullscreen:function(a){this.fullscreenMode=a===g?!this.fullscreenMode:a;this.remove();return this.create()},createMenu:function(a){var b=this.toolbar.get(a.name),
c=b.pos();a.x=c.x;a.y=c.y+b.height();if(a.selectedColor!==g){a.noColor=this.lang("noColor");this.menu=kb(a)}else{a.centerLineMode=false;this.menu=jb(a)}return this.menu},hideMenu:function(){this.beforeHideMenu();this.menu.remove();this.menu=null;return this},createDialog:function(a){var b=this;a.shadowMode=b.shadowMode;a.closeBtn={name:b.lang("close"),click:function(){b.hideDialog();b.focus()}};a.noBtn={name:b.lang("no"),click:function(){b.hideDialog();b.focus()}};return b.dialog=lb(a)},hideDialog:function(){this.dialog.remove();
this.dialog=null;return this}};U&&va<7&&za(document,"BackgroundImageCache",true);i.create=function(a,b){b||(b={});var c=i(a);if(c){b.srcElement=c[0];if(!b.width)b.width=c.width();if(!b.height)b.height=c.height();return(new ob(b)).create()}};i.plugin=function(a){pb.push(a)};i.lang=nb})(window);
KindEditor.plugin(function(q){var g=this;g.clickToolbar("source",function(){g.toolbar.disable();g.edit.design()});g.clickToolbar("fullscreen",function(){g.fullscreen()});g.clickToolbar("formatblock",function(){var A=g.lang("formatblock.formatBlock"),r={h1:28,h2:24,h3:18,H4:14,p:12},m=g.val("formatblock"),I=g.createMenu({name:"formatblock",width:g.langType=="en"?200:150});q.each(A,function(K,C){var L="font-size:"+r[K]+"px;";if(K.charAt(0)==="h")L+="font-weight:bold;";I.addItem({title:'<span style="'+
L+'">'+C+"</span>",height:r[K]+12,checked:m===K||m===C,click:function(){g.select().exec("formatblock","<"+K.toUpperCase()+">").hideMenu()}})})});g.clickToolbar("fontname",function(){var A=g.val("fontname"),r=g.createMenu({name:"fontname",width:150});q.each(g.lang("fontname.fontName"),function(m,I){r.addItem({title:'<span style="font-family: '+m+';">'+I+"</span>",checked:A===m.toLowerCase()||A===I.toLowerCase(),click:function(){g.exec("fontname",m).hideMenu()}})})});g.clickToolbar("fontsize",function(){var A=
g.val("fontsize");menu=g.createMenu({name:"fontsize",width:150});q.each(["9px","10px","12px","14px","16px","18px","24px","32px"],function(r,m){menu.addItem({title:'<span style="font-size:'+m+';">'+m+"</span>",height:q.removeUnit(m)+12,checked:A===m,click:function(){g.exec("fontsize",m).hideMenu()}})})});q.each("forecolor,hilitecolor".split(","),function(A,r){g.clickToolbar(r,function(){g.createMenu({name:r,selectedColor:g.val(r)||"default",click:function(m){g.exec(r,m).hideMenu()}})})});q.each("cut,copy,paste".split(","),
function(A,r){g.clickToolbar(r,function(){g.focus();try{g.exec(r,null)}catch(m){alert(g.lang(r+"Error"))}})});g.clickToolbar("about",function(){var A='<div style="margin:20px;"><div>KindEditor '+q.kindeditor+'</div><div>Copyright &copy; <a href="http://www.kindsoft.net/" target="_blank">kindsoft.net</a> All rights reserved.</div></div>';g.createDialog({name:"about",width:300,title:g.lang("about"),body:A})});q.each("selectall,justifyleft,justifycenter,justifyright,justifyfull,insertorderedlist,insertunorderedlist,indent,outdent,subscript,superscript,hr,print,bold,italic,underline,strikethrough,removeformat,unlink".split(","),
function(A,r){g.shortcutKeys[r]&&g.afterCreate(function(){q.ctrl(this.edit.doc,g.shortcutKeys[r],function(){g.clickToolbar(r)})});g.clickToolbar(r,function(){g.focus().exec(r,null)})})});
KindEditor.plugin(function(q){var g=this;g.clickToolbar("plainpaste",function(){var A='<div style="margin:10px;"><div style="margin-bottom:10px;">'+g.lang("plainpaste.").comment+'</div><textarea style="width:415px;height:260px;border:1px solid #A0A0A0;"></textarea></div>';A=g.createDialog({name:"plainpaste",width:450,title:g.lang("plainpaste"),body:A,yesBtn:{name:g.lang("yes"),click:function(){var m=r.val();m=q.escape(m);m=m.replace(/ /g,"&nbsp;");m=m.replace(/\r\n|\n|\r/g,"<br />$&");g.insertHtml(m).hideDialog().focus()}}});
var r=q("textarea",A.div());r.get().focus()})});
KindEditor.plugin(function(q){var g=this;g.clickToolbar("wordpaste",function(){var A='<div style="margin:10px;"><div style="margin-bottom:10px;">'+g.lang("wordpaste.").comment+'</div><iframe style="width:415px;height:260px;border:1px solid #A0A0A0;" frameborder="0"></iframe></div>';A=g.createDialog({name:"wordpaste",width:450,title:g.lang("wordpaste"),body:A,yesBtn:{name:g.lang("yes"),click:function(){var m=r.body.innerHTML;m=m.replace(/<meta(\n|.)*?>/ig,"");m=m.replace(/<!(\n|.)*?>/ig,"");m=m.replace(/<style[^>]*>(\n|.)*?<\/style>/ig,
"");m=m.replace(/<script[^>]*>(\n|.)*?<\/script>/ig,"");m=m.replace(/<w:[^>]+>(\n|.)*?<\/w:[^>]+>/ig,"");m=m.replace(/<xml>(\n|.)*?<\/xml>/ig,"");m=m.replace(/\r\n|\n|\r/ig,"");g.insertHtml(m).hideDialog().focus()}}}).div();A=q("iframe",A.get());var r=q.iframeDoc(A);if(!q.IE)r.designMode="on";r.open();r.write("<html><head><title>WordPaste</title></head>");r.write('<body style="background-color:#FFFFFF;font-size:12px;margin:2px;" />');q.IE||r.write("<br />");r.write("</body></html>");r.close();if(q.IE)r.body.contentEditable=
"true";A.get().contentWindow.focus()})});
KindEditor.plugin(function(q){var g=this;g.clickToolbar("link",function(){var A=g.lang("link."),r='<div style="margin:10px;"><div class="ke-dialog-row"><label for="keUrl">'+A.url+'</label><input type="text" id="keUrl" name="url" value="" style="width:90%;" /></div><div class="ke-dialog-row""><label for="keType">'+A.linkType+'</label><select id="keType" name="type"></select></div></div>';r=g.createDialog({name:"link",width:400,title:g.lang("link"),body:r,yesBtn:{name:g.lang("yes"),click:function(){g.exec("createlink",
m.val(),I.val()).hideDialog().focus()}}}).div();var m=q('input[name="url"]',r),I=q('select[name="type"]',r);I.get().options[0]=new Option(A.newWindow,"_blank");I.get().options[1]=new Option(A.selfWindow,"");m.val(g.val("createlink"));m.get().focus()})});
KindEditor.plugin(function(q){var g=this,A=g.emoticonsPath||g.scriptPath+"plugins/emoticons/images/",r=g.allowPreviewEmoticons===undefined?true:g.allowPreviewEmoticons,m=1;g.clickToolbar("emoticons",function(){function I(R,S,M){N?R.mouseover(function(){if(S>Z){N.css("left",0);N.css("right","")}else{N.css("left","");N.css("right",0)}da.attr("src",A+M+".gif");q(this).addClass("ke-plugin-emoticons-cell-on")}):R.mouseover(function(){q(this).addClass("ke-plugin-emoticons-cell-on")});R.mouseout(function(){q(this).removeClass("ke-plugin-emoticons-cell-on")});
R.click(function(ka){g.insertHtml('<img src="'+A+M+'.gif" border="0" alt="" />').hideMenu().focus();ka.stop()})}function K(R,S){var M=document.createElement("table");S.append(M);if(N){q(M).mouseover(function(){N.show()});q(M).mouseout(function(){N.hide()});X.push(q(M))}M.className="ke-plugin-emoticons-table";M.cellPadding=0;M.cellSpacing=0;M.border=0;for(var ka=(R-1)*sa+ca,ta=0;ta<O;ta++)for(var ua=M.insertRow(ta),ea=0;ea<$;ea++){var la=q(ua.insertCell(ea));la.addClass("ke-plugin-emoticons-cell");
I(la,ea,ka);var ba=q('<span class="ke-plugin-emoticons-img"></span>').css("background-position","-"+24*ka+"px 0px").css("background-image","url("+A+"static.gif)");la.append(ba);X.push(la);ka++}return M}function C(){q.each(X,function(){this.unbind()})}function L(R,S){R.click(function(M){C();aa.parentNode.removeChild(aa);Y.remove();aa=K(S,W);T(S);m=S;M.stop()})}function T(R){Y=q('<div class="ke-plugin-emoticons-page"></div>');W.append(Y);for(var S=1;S<=ia;S++){if(R!==S){var M=q('<a href="javascript:;">['+
S+"]</a>");L(M,S);Y.append(M);X.push(M)}else Y.append(q("@["+S+"]"));Y.append(q("@&nbsp;"))}}var O=5,$=9,ca=0,sa=O*$,ia=Math.ceil(135/sa),Z=Math.floor($/2),W=q('<div class="ke-plugin-emoticons-wrapper"></div>'),X=[];g.createMenu({name:"emoticons"}).div().append(W);var N,da;if(r){N=q('<div class="ke-plugin-emoticons-preview"></div>').css("right",0);da=q('<img class="ke-plugin-emoticons-preview-img" src="'+A+ca+'.gif" />');W.append(N);N.append(da)}var aa=K(m,W),Y;T(m);g.beforeHideMenu(function(){C()})})});
KindEditor.plugin(function(q){var g=this;q.undef(g.allowUpload,true);q.undef(g.allowFileManager,false);var A=q.undef(g.imageUploadJson,g.scriptPath+"php/upload_json.php"),r=this.scriptPath+"plugins/image/images/",m=g.lang("image.");g.clickToolbar("image",function(){var I=['<div style="margin:10px;"><div class="tabs"></div><iframe name="uploadIframe" style="display:none;"></iframe><form name="uploadForm" method="post" enctype="multipart/form-data" target="uploadIframe"><input type="hidden" name="referMethod" value="" /><div class="ke-dialog-row"><div class="tab1" style="display:none;">',
'<label for="keUrl">'+m.remoteUrl+"</label>",'<input type="text" id="keUrl" name="url" value="" style="width:230px;" />',' <input type="button" name="viewServer" value="'+m.viewServer+'" />','</div><div class="tab2" style="display:none;">','<label for="keFile">'+m.localUrl+"</label>",'<input type="file" id="keFile" name="imgFile" style="width:300px;" /></div></div><div class="ke-dialog-row">','<label for="keWidth">'+m.size+"</label>",m.width+' <input type="text" id="keWidth" name="width" value="" maxlength="4" style="width:50px;text-align:right;" /> ',
m.height+' <input type="text" name="height" value="" maxlength="4" style="width:50px;text-align:right;" /> ','<img src="'+r+'refresh.gif" width="16" height="16" alt="" />','</div><div class="ke-dialog-row">',"<label>"+m.align+"</label>",'<input type="radio" name="align" value="" checked="checked" /> <img name="defaultImg" src="'+r+'align_top.gif" width="23" height="25" alt="" />',' <input type="radio" name="align" value="left" /> <img name="leftImg" src="'+r+'align_left.gif" width="23" height="25" alt="" />',
' <input type="radio" name="align" value="right" /> <img name="rightImg" src="'+r+'align_right.gif" width="23" height="25" alt="" />','</div><div class="ke-dialog-row">','<label for="keTitle">'+m.imgTitle+"</label>",'<input type="text" id="keTitle" name="title" value="" style="width:95%;" /></div></div></form></div>'].join(""),K=g.createDialog({name:"image",width:450,height:300,title:g.lang("image"),body:I,yesBtn:{name:g.lang("yes"),click:function(){var W=L.val(),X=T.val(),N=O.val(),da=$.val(),aa=
"";ca.each(function(){if(this.checked){aa=this.value;return false}});if(C.selectedIndex===1){W=q('[name="uploadForm"]',K);var Y=q('[name="uploadIframe"]',K);W.attr("action",A);Y.bind("load",function(){Y.unbind();var R={};try{R=q.json(_iframeDoc(Y).body.innerHTML)}catch(S){alert(g.lang("invalidJson"))}if("error"in R)if(R.error===0)g.exec("insertimage",R.url,da,X,N,0,aa).hideDialog().focus();else{alert(R.message);return false}});W[0].submit()}else g.exec("insertimage",W,da,X,N,0,aa).hideDialog().focus()}}}).div(),
C=q.tabs({parent:q(".tabs",K),afterSelect:function(){}});C.add({title:m.remoteImage,panel:q(".tab1",K)});C.add({title:m.localImage,panel:q(".tab2",K)});C.select(0);var L=q('[name="url"]',K),T=q('[name="width"]',K),O=q('[name="height"]',K),$=q('[name="title"]',K),ca=q('[name="align"]');I=g.edit.cmd.range;var sa=I.startContainer,ia=I.startOffset;if(q.WEBKIT||I.isControl()){var Z=q(sa.childNodes[ia]);if(!(Z.name!=="img"||/^ke-\w+$/i.test(Z[0].className))){L.val(Z.attr("src"));T.val(Z.width());O.val(Z.height());
$.val(Z.attr("title"));ca.each(function(){if(this.value===Z.attr("align")){this.checked=true;return false}});L[0].focus()}}})});
KindEditor.plugin(function(q){var g=this,A=g.lang("flash.");g.clickToolbar("flash",function(){var r=['<div style="margin:10px;"><div class="ke-dialog-row">','<label for="keUrl">'+A.url+"</label>",'<input type="text" id="keUrl" name="url" value="" style="width:90%;" /></div><div class="ke-dialog-row">','<label for="keWidth">'+A.width+"</label>",'<input type="text" id="keWidth" name="width" value="550" maxlength="4" style="width:50px;text-align:right;" /> </div><div class="ke-dialog-row">','<label for="keHeight">'+
A.height+"</label>",'<input type="text" id="keHeight" name="height" value="400" maxlength="4" style="width:50px;text-align:right;" /> </div></div>'].join("");r=g.createDialog({name:"flash",width:400,height:200,title:g.lang("flash"),body:r,yesBtn:{name:g.lang("yes"),click:function(){var T=m.val();T=q.mediaImg(g.themesPath+"common/blank.gif",{src:T,type:q.mediaType(".swf"),width:I.val(),height:K.val(),quality:"high"});g.insertHtml(T).hideDialog().focus()}}}).div();var m=q('[name="url"]',r),I=q('[name="width"]',
r),K=q('[name="height"]',r);r=g.edit.cmd.range;var C=r.startContainer,L=r.startOffset;if(q.WEBKIT||r.isControl()){r=q(C.childNodes[L]);if(!(r.name!=="img"||r[0].className!=="ke-flash")){C=q.mediaAttrs(r.attr("kesrctag"));m.val(C.src);I.val(q.removeUnit(r.css("width"))||C.width||0);K.val(q.removeUnit(r.css("height"))||C.height||0);m[0].focus()}}})});
KindEditor.plugin(function(q){var g=this,A=g.lang("media.");g.clickToolbar("media",function(){var r=['<div style="margin:10px;"><div class="ke-dialog-row">','<label for="keUrl">'+A.url+"</label>",'<input type="text" id="keUrl" name="url" value="" style="width:90%;" /></div><div class="ke-dialog-row">','<label for="keWidth">'+A.width+"</label>",'<input type="text" id="keWidth" name="width" value="550" maxlength="4" style="width:50px;text-align:right;" /></div><div class="ke-dialog-row">','<label for="keHeight">'+
A.height+"</label>",'<input type="text" id="keHeight" name="height" value="400" maxlength="4" style="width:50px;text-align:right;" /></div><div class="ke-dialog-row">','<label for="keAutostart">'+A.autostart+"</label>",'<input type="checkbox" id="keAutostart" name="autostart" value="" /> </div></div>'].join("");r=g.createDialog({name:"media",width:400,height:230,title:g.lang("media"),body:r,yesBtn:{name:g.lang("yes"),click:function(){var O=m.val();O=q.mediaImg(g.themesPath+"common/blank.gif",{src:O,
type:q.mediaType(O),width:I.val(),height:K.val(),autostart:C[0].checked?"true":"false",loop:"true"});g.insertHtml(O).hideDialog().focus()}}}).div();var m=q('[name="url"]',r),I=q('[name="width"]',r),K=q('[name="height"]',r),C=q('[name="autostart"]',r);r=g.edit.cmd.range;var L=r.startContainer,T=r.startOffset;if(q.WEBKIT||r.isControl()){r=q(L.childNodes[T]);console.log(r[0].className);if(!(r.name!=="img"||!/^ke-\w+$/.test(r[0].className))){console.log(r[0].className);L=q.mediaAttrs(r.attr("kesrctag"));
m.val(L.src);I.val(q.removeUnit(r.css("width"))||L.width||0);K.val(q.removeUnit(r.css("height"))||L.height||0);C[0].checked=L.autostart==="true";m[0].focus()}}})});
